import Head from 'next/head'
import Header from '../components/Header'
import Main from '../components/Main'


export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor | E-commerce product page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" sizes="32x32" href="./images/favicon-32x32.png"/>
        <link
        rel="stylesheet"
        type="text/css"
        charset="UTF-8"
        href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
      />
      <link
        rel="stylesheet"
        type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
      />
      <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@400;700&display=swap" rel="stylesheet"></link>
      </Head>
      {/* <Menu/> */}
      <div className='md:px-40 h-full flex flex-col relative'>
        <Header/>
        <Main/>
      </div>
      
    </>
  )
}
